version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - raccoonecommerce-network

  raccoonecommerceapi:
    build:
      context: ./RaccoonEcommerceAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - raccoonecommerce-network
    volumes:
      - ./RaccoonEcommerceAPI/wwwroot/uploads:/app/wwwroot/uploads  
networks:
  raccoonecommerce-network:
    driver: bridge
